server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordersdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active:
      - "local"

  application:
    name: "orders"




