server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordersdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active:
      - "local"

  application:
    name: "orders"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery:
          timeout:
            ms: 120000
        enable:
          idempotence: true
        linger:
          ms: 0
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5
        request:
          timeout:
            ms: 30000






